title: 八雲日録 || まおーぶろぐ
subtitle: いくつになっても幼児並なまおーの日記
description: 雑な日々の雑な記録
keywords: null
author: 八雲
language: ja
timezone: Japan
url: 'https://www.ziomatrix.org'
root: /
#permalink: ':year:month:day_:title'
permalink: '/:year/:month/:day/:post_title.html'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':year/:year:month/:year:month:day_:title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 30
  order_by: '-date'
default_category: 日記
category_map: null
tag_map: null
date_format: YYYY/MM/DD
time_format: 'HH:mm:ss'
per_page: 30
pagination_dir: page
theme: next
deploy:
  type: null
